<a href="https://colab.research.google.com/github/MustafaEisaTech/Learning_TF/blob/main/how_to_create_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
# A tensor is a generalization of a scalar in the space
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [ ]:
#Initialization of a tensor
x = tf.constant(4.0, shape = (1, 1), dtype=tf.float32)
x = tf.constant([[1, 2, 3], [3, 4, 5]])
x = tf.ones((3, 3))# This initializes a tensor full of 0
x = tf.zeros((2, 3))# This initializes a tensor full of 0
x = tf.eye(3) # Eye for the identity matrix (I)
x = tf.random.normal((3, 3), mean = 0, stddev = 1)
x = tf.random.uniform((1, 3), minval = 0, maxval = 1)
x =tf.range(start = 1, limit = 10, delta = 2)
x = tf.cast(x, dtype = tf.float64)#dtpe = Data Type
#tf.float(16, 32, 64), tf.int(), tf.bool

#Mathematical operations
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x-y

z = tf.divide(x, y)
z = x/y

z = tf.multiply(x, y)
z = x*y

z = tf.tensordot(x, y, axes = 1)# The axes defines the dimensions for summation

z = tf.reduce_sum(x*y, axis = 0)


z = x**5

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
z = x@y


# Tensor indexing
x = tf.constant([0, 1, 1, 2, 1, 2, 3])
'''
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])
'''
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)


x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
#print(x[0, :])
#print(x[0:2, :])



#Tensor reshaping
x = tf.range(9)

#print(x)

x = tf.reshape(x, (3, 3))
print(x)

x = tf.transpose (x, perm = [1, 0])
print(x)




tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
